# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""
plugins=(git)

if [[ -n "${HOMEBREW_PREFIX:-}" ]]; then
  brew_share="$HOMEBREW_PREFIX/share"
  brew_opt="$HOMEBREW_PREFIX/opt"
fi

# extra tab completions
if [[ -n "${brew_share:-}" ]] && [[ -d "$brew_share/zsh-completions" ]]; then
  fpath=("$brew_share/zsh-completions" $fpath)
fi

if [[ -f "$ZSH/oh-my-zsh.sh" ]]; then
  source "$ZSH/oh-my-zsh.sh"
fi

# prompt
if [[ -n "${brew_share:-}" ]] && [[ -f "$brew_share/powerlevel10k/powerlevel10k.zsh-theme" ]]; then
  source "$brew_share/powerlevel10k/powerlevel10k.zsh-theme"
fi

# environment
export OPENCODE_DISABLE_DEFAULT_PLUGINS=true
export OPENCODE_SERVER_URL="http://127.0.0.1:4096"

# node
if command -v fnm >/dev/null 2>&1; then
  eval "$(fnm env --shell zsh --use-on-cd)"
fi

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# history (shared across terminals)
HISTSIZE=5000
HISTFILE="$HOME/.zsh_history"
SAVEHIST=$HISTSIZE
setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_SPACE
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_FIND_NO_DUPS

# completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
if [[ -n "${LS_COLORS:-}" ]]; then
  zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
fi
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# plugins
if [[ -n "${brew_opt:-}" ]] && [[ -f "$brew_opt/fzf-tab/share/fzf-tab/fzf-tab.zsh" ]]; then
  source "$brew_opt/fzf-tab/share/fzf-tab/fzf-tab.zsh"
fi

# fuzzy finder keybindings only (Ctrl-R, Ctrl-T, Alt-C)
if [[ -n "${brew_opt:-}" ]] && [[ -f "$brew_opt/fzf/shell/key-bindings.zsh" ]]; then
  source "$brew_opt/fzf/shell/key-bindings.zsh"
fi

# smarter directory jumping (z, zi)
if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi

# command autosuggestions
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(
  forward-char
  end-of-line
  vi-forward-char
  vi-end-of-line
  emacs-forward-word
  vi-forward-word
  vi-forward-word-end
  vi-add-eol
)
if [[ -n "${brew_share:-}" ]] && [[ -f "$brew_share/zsh-autosuggestions/zsh-autosuggestions.zsh" ]]; then
  source "$brew_share/zsh-autosuggestions/zsh-autosuggestions.zsh"
  bindkey '^[;' autosuggest-accept
fi

# syntax highlighting (keep this near the end of .zshrc)
if [[ -n "${brew_share:-}" ]] && [[ -f "$brew_share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]]; then
  source "$brew_share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi

# functions
function y() {
  local tmp cwd
  tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
  command yazi "$@" --cwd-file="$tmp"
  cwd="$(<"$tmp")"
  if [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && [ -d "$cwd" ]; then
    builtin cd -- "$cwd"
  fi
  rm -f -- "$tmp"
}

opencode() {
  if [[ "$#" -eq 0 ]]; then
    if [[ -n "${OPENCODE_SERVER_PASSWORD:-}" ]]; then
      command opencode attach "$OPENCODE_SERVER_URL" -p "$OPENCODE_SERVER_PASSWORD" --dir "$PWD"
    else
      command opencode attach "$OPENCODE_SERVER_URL" --dir "$PWD"
    fi
  else
    command opencode "$@"
  fi
}

# p10k configuration (generated by `p10k configure`)
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# machine-specific overrides and secrets
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
