#!/bin/sh

path=$1

[ -n "$path" ] || exit 0
path=${path%/}

if [ -z "$path" ]; then
  printf '/'
  exit 0
fi

case $path in
  "$HOME")
    printf '~'
    ;;
  *)
    printf '%s' "${path##*/}"
    ;;
esac
